openapi: 3.0.0
info:
  title: '立法院 API'
  version: 1.0.0
paths:
  /legislator:
    get:
      tags:
        - legislator
      summary: 歷屆立法委員資料
      operationId: 99342c5f3a8f0ecbf24785431be8401f
      parameters:
        -
          name: page
          in: query
          description: 頁數
          required: false
          schema:
            type: integer
          example: 1
        -
          name: limit
          in: query
          description: 每頁筆數
          required: false
          schema:
            type: integer
          example: 100
      responses:
        '200':
          description: 歷屆立法委員資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Legislator'
        '404':
          description: 找不到立法委員資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/legislator/{term}':
    get:
      tags:
        - legislator
      summary: '第 {term} 屆立法委員資料'
      operationId: 7839058e0b725ce8480fbaaacc31a7e7
      parameters:
        -
          name: term
          in: path
          description: 屆別
          required: true
          schema:
            type: integer
          example: 9
        -
          name: page
          in: query
          description: 頁數
          required: false
          schema:
            type: integer
          example: 1
        -
          name: limit
          in: query
          description: 每頁筆數
          required: false
          schema:
            type: integer
          example: 100
      responses:
        '200':
          description: '第 {term} 屆立法委員資料'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Legislator'
        '404':
          description: 找不到立法委員資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/legislator/{term}/{name}':
    get:
      tags:
        - legislator
      summary: 取得特定立法委員資料
      operationId: c4d714ab03730a6d5a81f2a39f896a8a
      parameters:
        -
          name: term
          in: path
          description: 屆別
          required: true
          schema:
            type: integer
          example: 9
        -
          name: name
          in: path
          description: 姓名
          required: true
          schema:
            type: string
          example: 王金平
      responses:
        '200':
          description: 立法委員資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Legislator'
        '404':
          description: 找不到立法委員資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /committee:
    get:
      tags:
        - committee
      summary: 委員會資料
      operationId: 8df59eb6ba4db5f74bd2f0cc73ac96aa
      responses:
        '200':
          description: 委員會資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Committee'
        '404':
          description: 找不到委員會資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/committee/{comtCd}':
    get:
      tags:
        - committee
      summary: 取得特定委員會資料
      operationId: 07625016084b45107a257093dce35bae
      parameters:
        -
          name: comtCd
          in: path
          description: '委員會 ID'
          required: true
          schema:
            type: integer
          example: 15
      responses:
        '200':
          description: 委員會資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Committee'
        '404':
          description: 找不到委員會資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /gazette:
    get:
      tags:
        - gazette
      summary: 取得依時間新至舊的公報
      operationId: 93235f6788c0a5acd733d84c5e0614eb
      parameters:
        -
          name: page
          in: query
          description: 頁數
          required: false
          schema:
            type: integer
          example: 1
        -
          name: limit
          in: query
          description: 每頁筆數
          required: false
          schema:
            type: integer
          example: 100
      responses:
        '200':
          description: 公報資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gazette'
  '/gazette/{comYear}':
    get:
      tags:
        - gazette
      summary: 取得特定年度的公報
      operationId: 2aa6343321b8d646314c8a832c13297e
      parameters:
        -
          name: comYear
          in: path
          description: 年度
          required: true
          schema:
            type: integer
          example: 109
        -
          name: page
          in: query
          description: 頁數
          required: false
          schema:
            type: integer
          example: 1
        -
          name: limit
          in: query
          description: 每頁筆數
          required: false
          schema:
            type: integer
          example: 100
      responses:
        '200':
          description: 公報資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gazette'
  '/gazette/{comYear}/{comVolume}':
    get:
      tags:
        - gazette
      summary: 取得特定年度卷號的公報
      operationId: 236933c2a8aabe3644db921c33315e34
      parameters:
        -
          name: comYear
          in: path
          description: 年度
          required: true
          schema:
            type: integer
          example: 109
        -
          name: comVolume
          in: path
          description: 卷號
          required: true
          schema:
            type: integer
          example: 1
        -
          name: page
          in: query
          description: 頁數
          required: false
          schema:
            type: integer
          example: 1
        -
          name: limit
          in: query
          description: 每頁筆數
          required: false
          schema:
            type: integer
          example: 100
      responses:
        '200':
          description: 公報資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gazette'
  '/gazette/{gazette_id}':
    get:
      tags:
        - gazette
      summary: 取得特定公報資料
      operationId: 8854a0900e158365a799e242a98b70fc
      parameters:
        -
          name: gazette_id
          in: path
          description: '公報 ID'
          required: true
          schema:
            type: string
          example: LCIDC01_1126203
      responses:
        '200':
          description: 公報資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gazette'
        '404':
          description: 找不到公報資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /gazette_agenda:
    get:
      tags:
        - gazette
      summary: 取得依時間新至舊的公報目錄
      operationId: 08b354684db6dcec0be51961873a8222
      parameters:
        -
          name: page
          in: query
          description: 頁數
          required: false
          schema:
            type: integer
          example: 1
        -
          name: limit
          in: query
          description: 每頁筆數
          required: false
          schema:
            type: integer
          example: 100
      responses:
        '200':
          description: 公報目錄資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GazetteAgenda'
  '/gazette_agenda/{gazette_id}':
    get:
      tags:
        - gazette
      summary: 取得公報下所有目錄
      operationId: 4564aa7a2b6b80dcca440603b90edbc0
      parameters:
        -
          name: gazette_id
          in: path
          description: '公報 ID'
          required: true
          schema:
            type: string
          example: LCIDC01_1126203
        -
          name: page
          in: query
          description: 頁數
          required: false
          schema:
            type: integer
          example: 1
        -
          name: limit
          in: query
          description: 每頁筆數
          required: false
          schema:
            type: integer
          example: 100
      responses:
        '200':
          description: 公報目錄資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GazetteAgenda'
  '/gazette_agenda/{agenda_id}':
    get:
      tags:
        - gazette
      summary: 取得特定公報目錄資料
      operationId: aa8875843b9348b0eda4ae3d8a47891e
      parameters:
        -
          name: agenda_id
          in: path
          description: '公報目錄 ID'
          required: true
          schema:
            type: string
          example: LCIDC01_1126203_0001
      responses:
        '200':
          description: 公報目錄資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GazetteAgenda'
        '404':
          description: 找不到公報目錄資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      required:
        - error
      properties:
        error:
          type: string
      type: object
    Legislator:
      properties:
        term:
          description: 屆別
          type: integer
        name:
          description: 姓名
          type: string
        ename:
          description: 英文姓名
          type: string
        sex:
          description: 性別
          type: string
        party:
          description: 黨籍
          type: string
        partyGroup:
          description: 黨團
          type: string
        areaName:
          description: 選區
          type: string
        committee:
          description: 委員會
          type: array
          items:
            type: string
        onboardDate:
          description: 就職日期
          type: string
        degree:
          description: 學歷
          type: array
          items:
            type: string
        experience:
          description: 經歷
          type: array
          items:
            type: string
        picUrl:
          description: 照片連結
          type: string
        leaveFlag:
          description: 離職否
          type: string
        leaveDate:
          description: 離職日期
          type: string
        leaveReason:
          description: 離職原因
          type: string
      type: object
    Committee:
      required:
        - comtCd
        - comtName
        - comtDesp
        - comtType
      properties:
        comtCd:
          description: 委員會代號
          type: string
        comtName:
          description: 委員會名稱
          type: string
        comtDesp:
          description: 委員會/職掌
          type: string
        comtType:
          description: '委員會類別(1:常設委員會,2:特種委員會,3:廢止委員會)'
          type: string
      type: object
    Gazette:
      required:
        - comYear
        - comVolume
        - comBookId
        - comDate
        - comTitle
        - comUrl
      properties:
        comYear:
          description: 年度
          type: integer
        comVolume:
          description: 卷號
          type: integer
        comBookId:
          description: 冊號
          type: integer
        gazette_id:
          description: '公報 ID'
          type: string
        agenda_api:
          description: '公報目錄 API'
          type: string
      type: object
    GazetteAgenda:
      required:
        - comYear
        - comVolume
        - comBookId
        - comDate
        - comTitle
        - comUrl
      properties:
        comYear:
          description: 卷
          type: integer
        comVolume:
          description: 期
          type: integer
        comBookId:
          description: 冊
          type: integer
        term:
          description: 屆
          type: integer
        sessionPeriod:
          description: 會期
          type: integer
        sessionTimes:
          description: 會次
          type: integer
        meetingTimes:
          description: 臨時會會次
          type: integer
        agendaNo:
          description: 目錄編號
          type: integer
        agendaType:
          description: '類別代碼(1:院會、2:國是論壇、3:委員會、4:質詢事項、5:議事錄、8:黨團協商紀錄、9:發言索引、10:報告事項、11:討論事項、12:臨時提案)'
          type: integer
        meetingDate:
          description: 會議日期
          type: array
          items:
            type: string
        subject:
          description: 案由
          type: string
        pageStart:
          description: 起頁
          type: integer
        pageEnd:
          description: 迄頁
          type: integer
        selectTerm:
          description: 選定屆別
          type: string
        agenda_id:
          description: '公報目錄 ID'
          type: string
        gazette_id:
          description: '公報 ID'
          type: string
      type: object
tags:
  -
    name: legislator
    description: 立法委員
  -
    name: committee
    description: 委員會
  -
    name: gazette
    description: 公報
